services:
  - type: web
    name: background-remover-bot
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
